<a href="https://colab.research.google.com/github/BNarayanaReddy/ML_Minor/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Data Preparation

In [2]:
np.random.seed(42)

In [3]:
height = np.random.normal(loc = 168, scale = 10, size=50) # average 168, deviation 10, size 50
weight = np.random.normal(loc = 68, scale = 5, size=50)

In [4]:
bmi = weight / (height/100)**2

In [5]:
labels = (bmi >= 25).astype(int) # obese = 1 else 0

In [6]:
labels

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1])

In [7]:
height = height.reshape(-1, 1)
weight = weight.reshape(-1, 1)

In [8]:
X = np.concatenate([height/np.max(height), weight/np.max(weight)], axis = 1)
X.shape

(50, 2)

In [9]:
Y = np.copy(labels).reshape(-1,1)

In [10]:
Y.shape

(50, 1)

Model Training

In [11]:
w = np.random.rand(2,1)*5
b = np.random.rand(1,1)*5
w.shape, b.shape

((2, 1), (1, 1))

In [12]:
def predict(X, w, b):
  return 1/(1+np.exp(-np.dot(X,w) + b))

In [13]:
def loss(Y_hat, Y):
  return np.mean((Y_hat - Y)**2)

In [14]:
Y_hat = predict(X, w, b)
print(loss(Y_hat, Y ))

0.40148758583968375


In [15]:
def compute_gradients(X, Y, w, b):
  dw = np.zeros(X.shape[1]).reshape(-1,1)
  db = np.zeros(Y.shape[1]).reshape(-1,1)
  for i in range(X.shape[0]):
    y_hat = predict(X, w, b)
    for j in range(X.shape[1]):
      dw[j] += (y_hat[i] - Y[i])*y_hat[i]*(1-y_hat[i])*X[i][j]
    db += (y_hat[i] - Y[i])*y_hat[i]*(1-y_hat[i])
  return dw, db

In [16]:
compute_gradients(X,Y, w, b)

(array([[1.46571625],
        [1.36250861]]),
 array([[1.5730925]]))

In [17]:
def fit(X, Y, w, b, epochs=100, lr=1):
  for epoch in range(epochs):
    dw, db = compute_gradients(X, Y, w, b)
    w = w - lr*dw
    b = b - lr*db
    if epoch %10 ==0:
      print(f'Loss: ', loss(predict(X,w,b), Y ))
  return w, b


In [18]:
fit(X, Y, w, b)

Loss:  0.3246827212965393
Loss:  0.23020561156945538
Loss:  0.21245336114023136
Loss:  0.20355819754621227
Loss:  0.20164131570428748
Loss:  0.1922776872179394
Loss:  0.18349882096541212
Loss:  0.18139458527270802
Loss:  0.18615690971357168
Loss:  0.19413376391303785


(array([[-2.42956636],
        [20.01360408]]),
 array([[15.89710259]]))

In [19]:
y_predicted = predict(X, *fit(X, Y, w, b, epochs = 100))

Loss:  0.3246827212965393
Loss:  0.23020561156945538
Loss:  0.21245336114023136
Loss:  0.20355819754621227
Loss:  0.20164131570428748
Loss:  0.1922776872179394
Loss:  0.18349882096541212
Loss:  0.18139458527270802
Loss:  0.18615690971357168
Loss:  0.19413376391303785


In [20]:
predictions = (y_predicted > 0.5).astype(int)

In [21]:
TP = np.sum((predictions == 1) & (Y == 1))
FP = np.sum((predictions == 1) & (Y == 0))
TN = np.sum((predictions == 0) & (Y == 0))
FN = np.sum((predictions == 0) & (Y == 1))


In [22]:
accuracy = ((TP + TN)/(TP+TN+FP+FN))*100

In [23]:
accuracy

np.float64(64.0)

In [24]:
precision = (TP + FP)/TP
precision

np.float64(1.5)

In [25]:
recall_sensitivity = TP/(TP+FN)
recall_sensitivity

np.float64(0.6153846153846154)

In [26]:
f1_score = (2*precision*recall_sensitivity)/(precision+recall_sensitivity)
f1_score

np.float64(0.8727272727272728)